let modeloJson = [
    {
      id: 1,
      name: 'Camiseta Rosa',
      img: 'img/1.png',
      price: 20.19,
      sizes: ['malha', 'algodão', 'dry'],
      description: 'Hardware de ultima geração!',
    },
    {
      id: 2,
      name: 'Camiseta amarela',
      img: 'img/2.png',
      price: 18.0,
      sizes: ['algodão', 'malha', 'dry'],
      description: 'Hardware de ultima geração!',
    },
    {
      id: 3,
      name: 'Camiseta Preta',
      img: 'img/3.png',
      price: 17.45,
      sizes: ['dry', 'malha', 'algodão'],
      description: 'Hardware de ultima geração!',
    },
    {
      id: 4,
      name: 'Camiseta Pink',
      img: 'img/4.png',
      price: 19.77,
      sizes: ['algodão', 'malha', 'dry'],
      description: 'Hardware de ultima geração!',
    },
    {
      id: 5,
      name: 'Camiseta Azul',
      img: 'img/5.png',
      price: 21.43,
      sizes: ['malha', 'algodão', 'dry'],
      description: 'Hardware de ultima geração!',
    },
    {
      id: 6,
      name: 'Camiseta Vermelha',
      img: 'img/6.png',
      price: 18.55,
      sizes: ['malha', 'dry', 'algodão'],
      description: 'Hardware de ultima geração!',
    },
    // {
    //   id: 7,
    //   name: 'Camiseta Marrom',
    //   img: 'img/camisetaM.jpg',
    //   price: 22.36,
    //   sizes: ['malha', 'dry', 'dry'],
    //   description: 'Blusa Básica Manga Curta',
    // },
  ];