let modeloJson = [
    {
      id: 1,
      name: 'Placa-mãe H510M-HVS',
      img: 'img/1.png',
      price: 399,
      sizes: ['malha', 'algodão', 'dry'],
      description: 'Placa mãe H510M-HVS, ótima placa para o seu pc gamer.',
    },
    {
      id: 2,
      name: 'GEFORCE RTX 2060',
      img: 'img/2.png',
      price: 1699,
      sizes: ['algodão', 'malha', 'dry'],
      description: 'RTX 2060, roda GTA V, Fortnite, CS GO, Valorant e muito mais em full hd.',
    },
    {
      id: 3,
      name: 'GEFORCE RTX 3090',
      img: 'img/3.png',
      price: 2999,
      sizes: ['dry', 'malha', 'algodão'],
      description: 'RTX 3090, roda todos os jogos da atualidade em ultra hd.',
    },
    {
      id: 4,
      name: 'Gabinete Gamer Led',
      img: 'img/4.png',
      price: 499,
      sizes: ['algodão', 'malha', 'dry'],
      description: 'O melhor gabinete para o seu pc gamer',
    },
    {
      id: 5,
      name: 'Memória RAM 18GB',
      img: 'img/5.png',
      price: 249.99,
      sizes: ['malha', 'algodão', 'dry'],
      description: 'Memória RAM de 16GB DDR4, ajuda o seu processador a rodar o mundo em ultra hd.',
    },
    {
      id: 6,
      name: 'Memória SSD 480GB',
      img: 'img/6.png',
      price: 289.79,
      sizes: ['malha', 'dry', 'algodão'],
      description: 'SSD de 480GB da Kingstom, alta velocidade de processamento e transferência de dados.',
    },
    // {
    //   id: 7,
    //   name: 'Camiseta Marrom',
    //   img: 'img/camisetaM.jpg',
    //   price: 22.36,
    //   sizes: ['malha', 'dry', 'dry'],
    //   description: 'Blusa Básica Manga Curta',
    // },
  ];